config/routes.rb
Rails.application.routes.draw do

  #roots to the logged in home page
  root 'posts#index'

  #creates the answer
  post '/users/:user_id/posts/:post_id' => 'answers#create'

  #sessions login/out
  resources :sessions, only: [:create, :destroy]
  
  #routes for users
  resources :users, only: [:show, :new, :create, :edit] do
    #nested routes for posts
    resources :posts, only: [:index, :new, :show, :create]
  end

  #nests the votes
  resources :answers, only: [] do
    member do
      put "like", to: "answers#upvote"
      put "dislike", to: "answers#downvote"
    end
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  belongs_to :question, class_name: "Post"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessor :password
  has_many :questions, class_name: "Post"
  has_many :answers
  has_secure_password
	  
  #validates presence of user paramaters on the create controller
  validates_presence_of :firstname, :on => :create
  validates_presence_of :lastname, :on => :create
  validates :password, length: { in: 6..20, message: "Length needs to be between 6 and 20 characters" }, allow_nil: true, :on => :create

  validates :email, :presence=> true, :uniqueness => true, :on => :create

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create 
     @user = User.find(params[:user_id])
     @post = Post.find(params[:post_id])
     @answer = @post.answers.new(answer_params)
     @answer.post_id
     if @answer.save
	    redirect_to root_path, notice: 'Answer successfully created'
     else 
	    render action 'new'
     end  
  end 

  def update 
  end 

  def destroy 
  end 

  def upvote
    @answer = Answer.find(params[:id])
    @answer.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @answer = Answer.find(params[:id])
    @answer.downvote_from current_user
    redirect_to :back
  end

  private 

  def set_comment
	  @answer = Answer.find(params[:id])
  end

  def answer_params
	  params.require(:answer).permit(:body)
  end 
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def current_user
    session[:user_id] ? User.find(session[:user_id]) : nil
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def home_page
    if !current_user
      @user = User.new
      render 'users/new'
    else 
      @posts = Post.all.order('created_at DESC')
      render 'posts/index'
    end
  end

  def index
    if !current_user
      redirect_to new_user_path
    end
    @posts = Post.all.order('created_at DESC')
  end 

  def new 
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save 

    redirect_to root_path
  end 

  def show 
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @answers = Answer.where(post_id: params[:id]).order(:cached_votes_score => :desc)
  end 

  def edit
  end 

  def update 
    @user = User.find(params[:session_id])
    @answer.upvote_by @user
    @answer.save
  end 

  def destroy
  end  

 def upvote 
   @answer.upvote_by current_user
   redirect_to :back 
 end

  private 
  def post_params 
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = if params[:email] then
      User.find_by(email: params[:email])
    else
      User.find(params[:id])
    end
    if @user and @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path @user
    else
      flash[:notice] = "Something went wrong"
      redirect_to root_path
    end
  end

  def destroy
    puts "DESTROYED"
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
    @user = User.new
  end

  #posts new user to the database
  def create
    user = User.create(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to root_path user 
    else
      flash[:notice] = "Form is invalid"
      redirect_to root_path
    end	
  end 

  #uses bcrypt to find email and match it to password
  def login
    @user = User.find_by_email(params[:email])
    if @user.password == params[:password]
      give_token
    else
      flash[:notice] = "Incorrect email/password combination"
      redirect_to login_path
    end
  end

  #shows the user with the id with the param users/:id 
  def show
    @user = User.find(params[:id])
    @posts = @user.questions
  end

  #GETS the User params for the edit action
  def edit
    @user = User.find(params[:id])
  end

  #PATCH/PUT User params for the update action
  def update
    puts "UPDATING"
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
    end
    redirect_to user_path
  end

  def destroy 
    @user.destroy
    redirect_to root_path
  end 

  private


  def set_user
    begin 
      @user = User.find(params[:id])
    rescue
      redirect_to root_path
    end 
  end

  #defines what paramaters are allowed to pass through user (as described by name)
  def user_params 
    params.require(:user).permit(
      :firstname,
      :lastname,
      :email,
      :password,
      :password_confirmation,
      :avatar
    )
  end 
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
  		session[:user_id] ? User.find(session[:user_id]) : nil
  	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= form_for :answer  do |f| %>
  <p>
    <%= f.label :body, class: "title-label", id: "label" %><br>
    <%= f.text_area :body %>
  </p>	
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/_login.html.erb
<% if !current_user %>
  <%= form_tag(sessions_path, method: :post, :id => 'signin') do |f|  %>
    <%= label_tag 'email' %>
    <%= email_field_tag :email %>
    <%= label_tag 'email' %>
    <%= password_field_tag :password %>
    <%= submit_tag "Login" %>
  <% end %>
<% else %>
  <ul class="nav navbar-nav">
    <% if current_user%>
      <li>
	<%= link_to "Profile", user_path(current_user) %>
      </li>
      <li>
	<%= link_to "Post", new_user_post_path(current_user.id) %>
      </li>
      <% end %>
      <li>
	<%= link_to "Logout", session_path(current_user.id), method: :delete %>
      </li>
  </ul>
<%end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="nav-barheader">
      <h2>NYCDA Overflow</h2>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
	<li><%= link_to 'Home', root_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
	<%= render 'layouts/login' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NYCDA</title>
  <link rel="stylesheet" type="text/css" href=https://cdnjs.cloudflare.com/ajax/libs/prism/0.0.1/prism.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/0.0.1/prism.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- BOOTSTRAP -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <!--    WMD    -->
  <link rel="stylesheet" type="text/css" href="wmd.css" />
  <script type="text/javascript" src="showdown.js"></script>
  
</head>

<header>
		<%= render 'layouts/nav'%>
</header>

<body>
	<br><br><br><br><br><br><br>

	<div class="col-md-1"></div>
	<div id="main_content" class="col-md-10"> 
		<%= flash[:notice] if flash[:notice] %>
		<%= yield %>
	</div>
	<div class="col-md-1"></div>

</body>
</html>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, user_post_path(current_user.id, post.id) %></h2>
    <p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Question</h1>
<div class="texteditor">
<%= form_for :post, url: user_posts_path do |f| %>
 		<p>
 			<%= f.label :title %><br>
 			<%= f.text_field :title %>
 		</p>
		<div id="wmd-button-bar" class="wmd-panel"></div><br/>
 		<p>
 			<%= f.label :body %><br>
 			<%= f.text_area :body, size: "24x6", id: "wmd-input" %>
 		</p>
 		<div id="wmd-preview" class="wmd-panel"></div>
		<br/>
		<div id="wmd-output" class="wmd-panel"></div>
 		<p>
 			<%= f.submit %>
 		</p>
<% end %>
</div>

app/views/posts/show.html.erb
<script src="../../assets/javascript/votes.js"></script>   
<h1><%= @post.title %></h1>
<br>
<pre>
  <code class="language-markup">
    <p><%= @post.body %></p>
  </code>
</pre>

<h2>Answers</h2>
	<br>
<% @answers.each do |answer| %>
  <br>
  <% @answer = Answer.find(answer) %>
  <%= link_to like_answer_path(@answer), :method => :put do %>
    <span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>
  <% end %>
  <h2><%= @answer.cached_votes_score %></h2>
  <%= link_to dislike_answer_path(@answer), :method => :put do %>
    <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
  <% end %>
  <pre>
    <code class="language-markup-ruby">
      <p>
	<%= @answer.body %>
      </p>
    </code>
  </pre>
<% end %>

<%= render 'answers/form' %>

<div id= "answers">
  <h2> <%= @post.answers.count %> Answers</h2>
  <h3>Add an answer</h3>
</div>

app/views/users/edit.html.erb
<% if current_user == @user %>
  <h1>Hello <%= @user.firstname %>, Edit your Account Information</h1>
    <%= form_for(:user, :url => {:controller => 'users', :action => 'update'}, :method => 'put') do |f| %>
      <p> First Name:</br> <%= f.text_field :firstname%> </p>
      <p> Last Name:</br> <%= f.text_field :lastname%> </p>
      <p> Email:</br> <%= f.email_field :email%> </p>
      <p> Password:</br> <%= f.password_field :password %></p>
      <p> Password Confirmation:</br> <%= f.password_field :password_confirmation%> </p>
      <%= f.file_field :avatar %>
      <br>
      <%= f.submit :Update %>
    <% end %>
<% else %>
  <p>Hello <%= current_user.firstname %>, this is not your profile page to edit</p>
<% end %>

app/views/users/new.html.erb
<% @page_title = "Signup" %>
<div class="Sign_Form">
  <h1>Sign Up</h1>
  <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
    <p> First Name:</br> <%= f.text_field :firstname%> </p>
    <p> Last Name:</br> <%= f.text_field :lastname%> </p>
    <p> Email:</br> <%= f.email_field :email%> </p>
    <p> Password:</br> <%= f.password_field :password %></p>
    <p> Password Confirmation:</br> <%= f.password_field :password_confirmation%> </p>
    <%= f.file_field :avatar %>
    <br>
    <%= f.submit :Signup %>
  <% end %>

  <% if @user.errors.any? %>
    <ul class="Signup_Errors">
    <% for message_error in @user.errors.full_messages %>
      <li>* <%= message_error %></li>
    <% end %>
    </ul>
  <% end %>

app/views/users/show.html.erb
<div id="info">
<br>
<p>First Name: <%= @user.firstname %></p>
<br>
<p>Last Name: <%= @user.lastname %></p>
<br>
<p>Email: <%= @user.email %></p>
<br>

<%= link_to 'Edit Profile', edit_user_path %>

</div>




<% @posts.each do |postvar| %>
<h1><%= link_to postvar.title, user_post_path(postvar.id, @user.id) %></h1>
<pre>
<code class="language-markup-ruby">
<p><%= postvar.body %></p>
</code>
</pre>
<br>
<% end %>